@startuml
left to right direction
skinparam classAttributeIconSize 0
title HandlePizza - Diagramme gestion du paiement

class "command" as Command {
  +id_command : Long
  +payment_amount : Float
  +payment_method : payment_method : String
  +payment_status : payment_status : String
  +command_status : command_status : String
  +command_type : command_type : String
}

class "customer" as Customer {
  +id_customer : Long
}

class "employe" as Employe {
  +id_employe : Long
  +fonction : String
}

class "delivery_man" as DeliveryMan

class "sales_point" as SalesPoint {
  +id_sales_point : Long
  +name : String
  +is_open : Boolean
}

enum "payment_method : String" as PaymentMethod {
  money
  paypal
  credit_card
}

enum "payment_status : String" as PaymentStatus {
  in_progress
  cancelled
  validate
}

enum "command_status : String" as CommandStatus {
  confirmed
  in_preparation
  ready_to_pick_up
  in_delivery
  delivered
  cancelled
}

enum "command_type : String" as CommandType {
  to_pickup
  to_delivery
}

' Aligné au diagramme global validé
Employe <|-- DeliveryMan

Customer "1" -- "0..*" Command
Employe "1" -- "0..*" Command
SalesPoint "1" o-- "0..*" Command

Command "*" -- "1" PaymentMethod : utilise
Command "*" -- "1" PaymentStatus : etat_paiement
Command "*" -- "1" CommandStatus : etat_commande
Command "*" -- "1" CommandType

@enduml
